PROG = qdcontour

CC = /usr/local/intel/compiler70/ia32/bin/icc

INCLUDES = -I $(includedir) -I $(includedir)/newbase -I $(includedir)/imagine
CFLAGS = -DUNIX $(INCLUDES) -w2 -Werror -wd981,810,383,1418,488,444,869

LIBS = -L$(libdir) -limagine -lnewbase -ljpeg -lpng -lz

# Common library compiling template

include ../../makefiles/makefile.prog
